name: Build Docker images

on:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Apache image
        uses: docker/build-push-action@v2
        with:
          context: apache
          push: false
          tags: mautic/docker-apache:latest
      - name: Build FPM image
        uses: docker/build-push-action@v2
        with:
          context: fpm
          push: false
          tags: mautic/docker-fpm:latest
